# Generated by Django 3.0.8 on 2020-07-22 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import receipt.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to=receipt.models.user_receipt_upload_path)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_on', '-updated_on'),
            },
        ),
    ]
