# Generated by Django 3.0.8 on 2020-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
