language: python
dist: bionic
python:
  - "3.8"
install:
  - pip install --upgrade pipenv
  - pipenv install
  - pipenv install coveralls tox-travis
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
notifications:
  email: false