# Generated by Django 3.0.8 on 2020-08-05 11:08

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200805_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.today),
        ),
    ]
