# Generated by Django 3.1 on 2020-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(default=list, null=True),
        ),
    ]
