# Generated by Django 3.1 on 2020-08-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200814_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='owner',
            new_name='author',
        ),
    ]
